import Head from "next/head";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>site Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" p-2">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi, nostrum
        magnam expedita qui vel deleniti minima enim eaque culpa pariatur
        adipisci earum, maxime ad. Illo dicta, enim ullam assumenda saepe
        pariatur quaerat reprehenderit! Blanditiis magnam tempora ratione
        obcaecati cumque magni maxime laborum aspernatur? Temporibus nam modi
        dolorem. Possimus, officia, nemo sit, impedit porro accusantium eaque
        quam ducimus culpa modi cupiditate dolor aut quae hic! Quo repudiandae
        sunt cum aliquam aliquid tempore voluptas. Fugiat mollitia
        exercitationem laborum incidunt culpa? Facere odio doloremque officiis
        ipsa sed ducimus, laboriosam pariatur, similique voluptates ea nesciunt
        mollitia obcaecati consequatur quaerat vero. Eum eos numquam vitae
        ducimus temporibus, quaerat illo corporis qui deserunt, quae totam
        exercitationem quisquam voluptate perferendis velit est fugit! Eum
        quibusdam placeat explicabo quaerat expedita asperiores illum nam,
        labore veniam id voluptatum suscipit mollitia alias quas? Unde eaque, ut
        atque necessitatibus nostrum similique maxime pariatur soluta enim et,
        porro maiores quos sunt natus obcaecati eligendi dolorum amet mollitia
        ad earum! Deleniti cum cupiditate quas vitae iste esse adipisci officiis
        consectetur temporibus. Nobis accusamus rem repellat itaque maxime
        blanditiis unde earum architecto quas, quam consectetur facilis officiis
        molestiae. Nulla eum, praesentium repudiandae debitis unde similique
        omnis quas reprehenderit. Earum ratione corporis quam temporibus
        doloribus?
      </div>
    </div>
  );
}
